import {
  BsArrow90DegDown,
  BsArrow90DegUp,
  BsBag,
  BsEnvelopeArrowDown,
  BsHouse,
  BsInfoCircle,
  BsMoonStars,
  BsPatchCheckFill,
  BsPatchExclamationFill,
  BsPeople,
  BsPlusCircleDotted,
  BsReceipt,
  BsShop,
  BsSunFill,
  BsTrash,
  BsUpload,
  BsWebcam,
  BsX,
  BsTwitter,
  BsFacebook,
  BsGithub,
  BsInstagram,
  BsArrowDown,
  BsChevronExpand,
  BsUsbC,
  BsCheckLg,
  BsPencil,
} from "react-icons/bs";
export const Icon = {
  upArrow: BsArrow90DegDown,
  downtArrow: BsArrowDown,
  expandArrow: BsChevronExpand,
  moon: BsMoonStars,
  sun: BsSunFill,
  info: BsInfoCircle,
  upload: BsUpload,
  trash: BsTrash,
  X: BsX,
  plusCircleDotted: BsPlusCircleDotted,
  home: BsHouse,
  shop: BsShop,
  receipt: BsReceipt,
  website: BsWebcam,
  envelopeArrowDown: BsEnvelopeArrowDown,
  people: BsPeople,
  bag: BsBag,
  verified: BsPatchCheckFill,
  unverifed: BsPatchExclamationFill,
  twitter: BsTwitter,
  facebook: BsFacebook,
  github: BsGithub,
  instagram: BsInstagram,
  list: BsUsbC,
  checked: BsCheckLg,
  pencil: BsPencil,
} as const;
